const PROTECTION_META = [
  { key: "antiRaid", name: "منع الهجمات الجماعية", group: "هجمات" },
  { key: "antiSpam", name: "منع السبام", group: "شات" },
  { key: "antiFlood", name: "منع التكرار", group: "شات" },
  { key: "antiLink", name: "منع الروابط", group: "شات" },
  { key: "antiInvite", name: "منع دعوات السيرفرات", group: "شات" },
  { key: "antiToxic", name: "منع الكلمات المسيئة", group: "شات" },
  { key: "antiCapslock", name: "منع الأحرف الكبيرة", group: "شات" },
  { key: "antiMassMention", name: "منع المنشن الجماعي", group: "شات" },
  { key: "antiGhostPing", name: "كشف الشبح منشن", group: "شات" },
  { key: "antiBot", name: "منع البوتات", group: "أعضاء" },
  { key: "antiSelfbot", name: "كشف السيلف بوت", group: "أعضاء" },
  { key: "antiAlts", name: "منع الحسابات الوهمية", group: "أعضاء" },
  { key: "antiNickname", name: "حماية الاختصارات", group: "أعضاء" },
  { key: "antiWebhook", name: "منع الويهوك", group: "سيرفر" },
  { key: "antiChannelDelete", name: "حماية الرومات", group: "سيرفر" },
  { key: "antiChannelCreate", name: "منع الرومات الجديدة", group: "سيرفر" },
  { key: "antiRoleDelete", name: "حماية الرتب", group: "سيرفر" },
  { key: "antiRoleCreate", name: "منع الرتب الجديدة", group: "سيرفر" },
  { key: "antiEmojiDelete", name: "حماية الإيموجي", group: "سيرفر" },
  { key: "antiEmojiCreate", name: "منع إيموجي جديد", group: "سيرفر" },
  { key: "antiStickerDelete", name: "حماية الملصقات", group: "سيرفر" },
  { key: "antiStickerCreate", name: "منع ملصقات جديدة", group: "سيرفر" },
  { key: "antiIntegration", name: "حماية التكاملات", group: "سيرفر" },
  { key: "antiVanity", name: "حماية الرابط المخصص", group: "سيرفر" },
  { key: "permissionGuard", name: "حماية الصلاحيات", group: "سيرفر" },
  { key: "antiBan", name: "منع الحظر غير المصرح", group: "إشراف" },
  { key: "antiKick", name: "منع الطرد غير المصرح", group: "إشراف" },
  { key: "antiPrune", name: "منع التنظيف الجماعي", group: "إشراف" },
  { key: "antiMassBan", name: "منع الحظر الجماعي", group: "إشراف" },
  { key: "antiMassKick", name: "منع الطرد الجماعي", group: "إشراف" },
];

export { PROTECTION_META };
